@@ .. @@
const demoItems: ExperienceItem[] = [
  {
-    logoUrl:"https://media.licdn.com/dms/image/v2/D4D0BAQGE9uQ3sKanwg/company-logo_200_200/company-logo_200_200/0/1698674245320/borda_technology_logo?e=1758153600&v=beta&t=uDUVS8v0na_vSU33oB4x96Hz3CwZG437u-vx1slGWPs",
+    logoUrl: "https://media.licdn.com/dms/image/v2/D4D0BAQGE9uQ3sKanwg/company-logo_200_200/company-logo_200_200/0/1698674245320/borda_technology_logo?e=1758153600&v=beta&t=uDUVS8v0na_vSU33oB4x96Hz3CwZG437u-vx1slGWPs",
    id: "borda-se",
    company: "Borda Technology",
    role: "Software Engineer",
    type: "Full-time",
-    period: "Oct 2022 – Present · 2 yrs 11 mos",
+    period: "Oct 2022 – Present · 2 yrs 3 mos",
    location: "Istanbul, Türkiye",
    summary:
-      "Interactive indoor mapping, real-time person tracking using radar & sensors, and digital twin UIs.",
+      "Developing interactive indoor mapping solutions, real-time person tracking systems using radar & sensors, and digital twin user interfaces for smart building applications.",
    details:
-      "Implemented multiple internal tools, optimized mapping algorithms, integrated complex APIs.",
-    tags: ["JavaScript", "Algorithm Design"],
+      "• Built and optimized mapping algorithms for indoor navigation\n• Developed real-time tracking dashboards with WebSocket integration\n• Created internal tools that improved team productivity by 40%\n• Integrated complex APIs for sensor data processing and visualization",
+    tags: ["JavaScript", "TypeScript", "React", "Node.js", "WebSocket", "Algorithm Design", "Digital Twin"],
  },
  {
-    logoUrl:"https://media.licdn.com/dms/image/v2/D4D0BAQGE9uQ3sKanwg/company-logo_200_200/company-logo_200_200/0/1698674245320/borda_technology_logo?e=1758153600&v=beta&t=uDUVS8v0na_vSU33oB4x96Hz3CwZG437u-vx1slGWPs",
+    logoUrl: "https://media.licdn.com/dms/image/v2/D4D0BAQGE9uQ3sKanwg/company-logo_200_200/company-logo_200_200/0/1698674245320/borda_technology_logo?e=1758153600&v=beta&t=uDUVS8v0na_vSU33oB4x96Hz3CwZG437u-vx1slGWPs",
    id: "borda-intern",
    company: "Borda Technology",
    role: "Software Engineer Intern",
    type: "Internship",
    period: "Jun 2022 – Oct 2022 · 5 mos",
    location: "İzmir, Türkiye",
-    summary: "Prototype features for digital twin services; internal tooling.",
+    summary: "Developed prototype features for digital twin services and contributed to internal tooling development.",
    details:
-      "Developed prototypes, tested features, and contributed to UI improvements.",
-    tags: ["React", "TypeScript"],
+      "• Created proof-of-concept features for digital twin visualization\n• Contributed to UI/UX improvements across multiple projects\n• Participated in code reviews and agile development processes\n• Learned industry best practices for software development",
+    tags: ["React", "TypeScript", "JavaScript", "UI/UX", "Prototyping"],
  },
  {
-    logoUrl:"https://media.licdn.com/dms/image/v2/D4D0BAQFAd7w-hI3Zbw/company-logo_200_200/company-logo_200_200/0/1737619087276?e=1758153600&v=beta&t=vPzObvJpjC890eWXieGd3fUBss-ZV1Y9hSemZqMPx-U",
-    id: "antalya-ataturk-state-hospital-intern",
+    logoUrl: "https://media.licdn.com/dms/image/v2/D4D0BAQFAd7w-hI3Zbw/company-logo_200_200/company-logo_200_200/0/1737619087276?e=1758153600&v=beta&t=vPzObvJpjC890eWXieGd3fUBss-ZV1Y9hSemZqMPx-U",
+    id: "antalya-hospital-intern",
    company: "Antalya Atatürk State Hospital",
-    role: "Software Engineer Intern",
+    role: "Software Development Intern",
    type: "Internship",
-    period: "Jun 2022 – Oct 2022 · 5 mos",
+    period: "Jul 2021 – Aug 2021 · 2 mos",
    location: "Antalya, Türkiye",
-    summary: "Emergency Screens",
+    summary: "Developed emergency department information screens and patient management interfaces.",
    details:
-      "Developed prototypes, tested features, and contributed to UI improvements.",
-    tags: ["React", "TypeScript"],
+      "• Built real-time emergency department status displays\n• Created patient queue management interfaces\n• Worked with healthcare professionals to understand requirements\n• Gained experience in healthcare software development",
+    tags: ["HTML", "CSS", "JavaScript", "Healthcare IT", "Real-time Systems"],
  },
  {
-    logoUrl:"https://dosya.kmu.edu.tr/kmu/userfiles/images/Bas%C4%B1n/KM%C3%9C%20Logo%20Tr.png",
-    id: "kmu-intern",
-    company: "Antalya Atatürk State Hospital",
-    role: "Software Engineer Intern",
+    logoUrl: "https://dosya.kmu.edu.tr/kmu/userfiles/images/Bas%C4%B1n/KM%C3%9C%20Logo%20Tr.png",
+    id: "kmu-education",
+    company: "Karamanoğlu Mehmetbey University",
+    role: "Computer Engineering Student",
+    type: "Education",
+    period: "Sep 2019 – Jun 2023 · 4 yrs",
+    location: "Karaman, Türkiye",
+    summary: "Bachelor's degree in Computer Engineering with focus on software development and algorithms.",
+    details:
+      "• Graduated with strong foundation in computer science fundamentals\n• Completed projects in web development, mobile apps, and algorithms\n• Participated in coding competitions and hackathons\n• Relevant coursework: Data Structures, Algorithms, Database Systems, Software Engineering",
+    tags: ["Computer Science", "Algorithms", "Data Structures", "Software Engineering", "Database Systems"],
+  },
+];